export enum CONTEXT_NAME {
  WMS = "WMS",
  TEST = "TEST"
}

export enum OPERATION_NAME {
  OFFLOAD = "OFFLOAD",
  LINK_CONTAINERS = "LINK_CONTAINERS",
  UPLOAD_DOs = "UPLOAD_DOs",
  GENERATE_PICKLISTS = "GENERATE_PICKLISTS",
  ASSIGN_PICKLIST = "ASSIGN_PICKLIST",
  PICK_UP = "PICK_UP",
  MARK_FOR_QA = "MARK_FOR_QA",
  POST_FOR_QA = "POST_FOR_QA",
  POST_FOR_USABLE = "POST_FOR_USABLE",
  DELETE_DO = "DELETE_DO",
  MARK_DISPATCH_READY = "MARK_DISPATCH_READY",
  DISPATCH_PICKLIST = "DISPATCH_PICKLIST",

  TEST = "TEST"
}

export enum OPERATION_LOCATION {
  OFFLOAD = 0,
  LINK_CONTAINERS = 1,
  UPLOAD_DOs = 2,
  GENERATE_PICKLISTS = 3,
  ASSIGN_PICKLIST = 4,
  PICK_UP = 5,
  MARK_FOR_QA = 6,
  POST_FOR_QA = 7,
  POST_FOR_USABLE = 8,
  DELETE_DO = 9,
  MARK_DISPATCH_READY = 10,
  DISPATCH_PICKLIST = 11,
  TEST = 12
}

export interface IApplicationWMS {
  context: CONTEXT_NAME.WMS
  operation: OPERATION_NAME
  location: OPERATION_LOCATION
}

export const RESOURCE_LOCK_STATUS = {
  LOCKED: "locked",
  UNLOCKED: "unlocked",
  FAILED_TRYING: "failedTrying"
}

export enum RESOURCE_LOCK_ATTEMPT {
  TIMEOUT_LIMIT = 4,
  ATTEMPT_ACQUIRING_LOCK_COUNT = 1000
}
